// Данные фильмов.
const movies = [
  {
    id: 1,
    title: `Silent Hill`,
    originalTitle: `Silent Hill`,
    year: 2006,
    duration: `2h 5m`,
    genre: `Horror`,
    ageLimit: `R`,
    releaseDate: `21 April 2006`,
    country: `Canada`,
    story: `Routed from sleepwalking problems, Rose Da Silva decides to take her daughter Sharon to the town she talks about in her sleep, Silent Hill, to face her nightmares, where Sharon goes missing and Rose must fight the power of the town to get her back.`,
    posterURL: `https://m.media-amazon.com/images/M/MV5BOWQzNTU3NGUtNDAxMi00ZjFjLTkyYWUtYjgwZDJiMDljZWY4XkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_SY1000_CR0,0,675,1000_AL_.jpg`,
    rating: 6.6,
    commentsNumber: 91
  },
  {
    id: 2,
    title: `The Hangover`,
    originalTitle: `The Hangover`,
    year: 2009,
    duration: `1h 40m`,
    genre: `Comedy`,
    ageLimit: `R`,
    releaseDate: `30 May 2009`,
    country: `USA`,
    story: `Three buddies wake up from a bachelor party in Las Vegas, with no memory of the previous night and the bachelor missing. They make their way around the city in order to find their friend before his wedding.`,
    posterURL: `https://m.media-amazon.com/images/M/MV5BNGQwZjg5YmYtY2VkNC00NzliLTljYTctNzI5NmU3MjE2ODQzXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX675_CR0,0,675,999_AL_.jpg`,
    rating: 7.7,
    commentsNumber: 20
  },
  {
    id: 3,
    title: `The Martian`,
    originalTitle: `The Martian`,
    year: 2015,
    duration: `2h 24m`,
    genre: `Sci-fi`,
    ageLimit: `PG-13`,
    releaseDate: `11 September 2015`,
    country: `USA`,
    story: `After a massive storm forces his crew to leave the planet, an astronaut, Mark Watney, is marooned on Mars, and presumed dead. Figuring that it would be at least four years until someone can rescue him, he sets out, though often ingenious means, to survive...`,
    posterURL: `https://m.media-amazon.com/images/M/MV5BMTc2MTQ3MDA1Nl5BMl5BanBnXkFtZTgwODA3OTI4NjE@._V1_SY1000_CR0,0,675,1000_AL_.jpg`,
    rating: 8.0,
    commentsNumber: 33
  },
  {
    id: 4,
    title: `I Am Legend`,
    originalTitle: `I Am Legend`,
    year: 2007,
    duration: `1h 41m`,
    genre: `Horror`,
    ageLimit: `PG-13`,
    releaseDate: `14 December 2007`,
    country: `USA`,
    story: `It is the year 2012. In the ruins of New York city. Robert Neville is a military scientist who is the lone survivor of a biochemical disease which was supposed to cure cancer 3 years previous. With only blood thirsty zombies as his neighbors and his trusty dog, Samantha, Robert is trying to discover a cure for this disease and to find out any other people who might have also survived.`,
    posterURL: `https://m.media-amazon.com/images/M/MV5BYTE1ZTBlYzgtNmMyNS00ZTQ2LWE4NjEtZjUxNDJkNTg2MzlhXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SY1000_SX675_AL_.jpg`,
    rating: 7.2,
    commentsNumber: 66
  },
  {
    id: 5,
    title: `Whiplash`,
    originalTitle: `Whiplash`,
    year: 2014,
    duration: `1h 46m`,
    genre: `Music`,
    ageLimit: `R`,
    releaseDate: `16 January 2014`,
    country: `USA`,
    story: `A promising young drummer enrolls at a cut-throat music conservatory where his dreams of greatness are mentored by an instructor who will stop at nothing to realize a student's potential.`,
    posterURL: `https://m.media-amazon.com/images/M/MV5BOTA5NDZlZGUtMjAxOS00YTRkLTkwYmMtYWQ0NWEwZDZiNjEzXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX675_CR0,0,675,999_AL_.jpg`,
    rating: 8.5,
    commentsNumber: 94
  },
  {
    id: 6,
    title: `Oldboy`,
    originalTitle: `Oldboy`,
    year: 2003,
    duration: `2h`,
    genre: `Drama`,
    ageLimit: `R`,
    releaseDate: `21 November 2003`,
    country: `South Korea`,
    story: `An average man is kidnapped and imprisoned in a shabby cell for 15 years without explanation. He then is released, equipped with money, a cellphone and expensive clothes. As he strives to explain his imprisonment and get his revenge, Oh Dae-Su soon finds out that his kidnapper has a greater plan for him and is set onto a path of pain and suffering in an attempt to uncover the motive of his mysterious tormentor.`,
    posterURL: `https://m.media-amazon.com/images/M/MV5BMTI3NTQyMzU5M15BMl5BanBnXkFtZTcwMTM2MjgyMQ@@._V1_.jpg`,
    rating: 8.4,
    commentsNumber: 50
  },
  {
    id: 7,
    title: `Ghost in the Shell`,
    originalTitle: `Ghost in the Shell`,
    year: 1995,
    duration: `1h 23m`,
    genre: `Animation`,
    ageLimit: `Not Rated`,
    releaseDate: `18 November 1995`,
    country: `Japan`,
    story: `It is the year 2029. Technology has advanced so far that cyborgs are commonplace. In addition, human brains can connect to the internet directly. Major Motoko Kasunagi is an officer in Section 9, an elite, secretive police division that deals with special operations, including counter terrorism and cyber crime. She is currently on the trail of the Puppet Master, a cyber criminal who hacks into the brains of cyborgs in order to obtain information and to commit other crimes.`,
    posterURL: `https://m.media-amazon.com/images/M/MV5BYWRiYjQyOGItNzQ1Mi00MGI1LWE3NjItNTg1ZDQwNjUwNDM2XkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_.jpg`,
    rating: 8.0,
    commentsNumber: 101
  },
  {
    id: 8,
    title: `It`,
    originalTitle: `It`,
    year: 2017,
    duration: `2h 15m`,
    genre: `Horror`,
    ageLimit: `R`,
    releaseDate: `5 September 2017`,
    country: `USA`,
    story: `In the summer of 1989, a group of bullied kids band together to destroy a shape-shifting monster, which disguises itself as a clown and preys on the children of Derry, their small Maine town.`,
    posterURL: `https://m.media-amazon.com/images/M/MV5BZDVkZmI0YzAtNzdjYi00ZjhhLWE1ODEtMWMzMWMzNDA0NmQ4XkEyXkFqcGdeQXVyNzYzODM3Mzg@._V1_SY1000_CR0,0,666,1000_AL_.jpg`,
    rating: 7.4,
    commentsNumber: 39
  },
  {
    id: 9,
    title: `Lock, Stock and Two Smoking Barrels`,
    originalTitle: `Lock, Stock and Two Smoking Barrels`,
    year: 1998,
    duration: `1h 47m`,
    genre: `Comedy`,
    ageLimit: `R`,
    releaseDate: `28 August 1998`,
    country: `UK`,
    story: `A botched card game in London triggers four friends, thugs, weed-growers, hard gangsters, loan sharks and debt collectors to collide with each other in a series of unexpected events, all for the sake of weed, cash and two antique shotguns.`,
    posterURL: `https://m.media-amazon.com/images/M/MV5BMTAyN2JmZmEtNjAyMy00NzYwLThmY2MtYWQ3OGNhNjExMmM4XkEyXkFqcGdeQXVyNDk3NzU2MTQ@._V1_SY1000_CR0,0,666,1000_AL_.jpg`,
    rating: 8.2,
    commentsNumber: 54
  },
  {
    id: 10,
    title: `Fight Club`,
    originalTitle: `Fight Club`,
    year: 1999,
    duration: `2h 19m`,
    genre: `Drama`,
    ageLimit: `R`,
    releaseDate: `10 September 1999`,
    country: `USA`,
    story: `An insomniac man who is an ordinary worker of a huge company, an IKEA buyer and classic consumer of capitalist system is very bored of his ordinary and routine life and meets with a person that is totally who he wants to be. And after that his life changes, with his new friend he creates a fight club that is gonna evolve very big movement all over country that even he can't imagine.`,
    posterURL: `https://m.media-amazon.com/images/M/MV5BMjJmYTNkNmItYjYyZC00MGUxLWJhNWMtZDY4Nzc1MDAwMzU5XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SY1000_CR0,0,676,1000_AL_.jpg`,
    rating: 8.8,
    commentsNumber: 71
  },
  {
    id: 11,
    title: `The Fifth Element`,
    originalTitle: `The Fifth Element`,
    year: 1997,
    duration: `2h 6m`,
    genre: `Action`,
    ageLimit: `PG-13`,
    releaseDate: `7 May 1997`,
    country: `France`,
    story: `In the colorful future, a cab driver unwittingly becomes the central figure in the search for a legendary cosmic weapon to keep Evil and Mr. Zorg at bay.`,
    posterURL: `https://m.media-amazon.com/images/M/MV5BZWFjYmZmZGQtYzg4YS00ZGE5LTgwYzAtZmQwZjQ2NDliMGVmXkEyXkFqcGdeQXVyNTUyMzE4Mzg@._V1_SY1000_CR0,0,696,1000_AL_.jpg`,
    rating: 7.7,
    commentsNumber: 64
  },
  {
    id: 12,
    title: `Nightcrawler`,
    originalTitle: `Nightcrawler`,
    year: 2014,
    duration: `1h 57m`,
    genre: `Crime`,
    ageLimit: `R`,
    releaseDate: `5 September 2014`,
    country: `USA`,
    story: `When Louis Bloom, a con man desperate for work, muscles into the world of L.A. crime journalism, he blurs the line between observer and participant to become the star of his own story.`,
    posterURL: `https://m.media-amazon.com/images/M/MV5BN2U1YzdhYWMtZWUzMi00OWI1LWFkM2ItNWVjM2YxMGQ2MmNhXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg`,
    rating: 7.9,
    commentsNumber: 39
  },
  {
    id: 13,
    title: `Scarface`,
    originalTitle: `Scarface`,
    year: 1983,
    duration: `2h 50m`,
    genre: `Crime`,
    ageLimit: `R`,
    releaseDate: `1 December 1983`,
    country: `USA`,
    story: `In Miami in 1980, a determined Cuban immigrant takes over a drug cartel and succumbs to greed.`,
    posterURL: `https://m.media-amazon.com/images/M/MV5BNjdjNGQ4NDEtNTEwYS00MTgxLTliYzQtYzE2ZDRiZjFhZmNlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SY1000_CR0,0,666,1000_AL_.jpg`,
    rating: 8.3,
    commentsNumber: 50
  },
  {
    id: 14,
    title: `The Last Samurai`,
    originalTitle: `The Last Samurai`,
    year: 2003,
    duration: `2h 34m`,
    genre: `Drama`,
    ageLimit: `R`,
    releaseDate: `20 November 2003`,
    country: `USA`,
    story: `In Japan, Civil War veteran Captain Nathan Algren trains the Emperor's troops to use modern weapons as they prepare to defeat the last of the country's samurais. But Algren's passion is swayed when he is captured by the samurai and learns about their traditions and code of honor.`,
    posterURL: `https://m.media-amazon.com/images/M/MV5BMzkyNzQ1Mzc0NV5BMl5BanBnXkFtZTcwODg3MzUzMw@@._V1_SY1000_CR0,0,675,1000_AL_.jpg`,
    rating: 7.7,
    commentsNumber: 47
  },
  {
    id: 15,
    title: `Apocalypto`,
    originalTitle: `Apocalypto`,
    year: 2006,
    duration: `2h 19m`,
    genre: `Adventure`,
    ageLimit: `R`,
    releaseDate: `8 December 2006`,
    country: `USA`,
    story: `In the Maya civilization, a peaceful tribe is brutally attacked by warriors seeking slaves and human beings for sacrifice for their gods. Jaguar Paw hides his pregnant wife and his son in a deep hole nearby their tribe and is captured while fighting with his people. An eclipse spares his life from the sacrifice and later he has to fight to survive and save his beloved family.`,
    posterURL: `https://m.media-amazon.com/images/M/MV5BMzhmNGMzMDMtZDM0Yi00MmVmLWExYjAtZDhjZjcxZDM0MzJhXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SY1000_CR0,0,674,1000_AL_.jpg`,
    rating: 7.8,
    commentsNumber: 85
  },
  {
    id: 16,
    title: `RoboCop`,
    originalTitle: `RoboCop`,
    year: 1987,
    duration: `1h 42m`,
    genre: `Sci-Fi`,
    ageLimit: `R`,
    releaseDate: `17 July 1987`,
    country: `USA`,
    story: `In a dystopic and crime-ridden Detroit, a terminally wounded cop returns to the force as a powerful cyborg haunted by submerged memories.`,
    posterURL: `https://m.media-amazon.com/images/M/MV5BZWVlYzU2ZjQtZmNkMi00OTc3LTkwZmYtZDVjNmY4OWFmZGJlXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SY1000_CR0,0,644,1000_AL_.jpg`,
    rating: 7.6,
    commentsNumber: 111
  },
  {
    id: 17,
    title: `The Social Network`,
    originalTitle: `The Social Network`,
    year: 2010,
    duration: `2h`,
    genre: `Biography`,
    ageLimit: `PG-13`,
    releaseDate: `24 September 2010`,
    country: `USA`,
    story: `On a fall night in 2003, Harvard undergrad and computer programming genius Mark Zuckerberg sits down at his computer and heatedly begins working on a new idea. In a fury of blogging and programming, what begins in his dorm room soon becomes a global social network and a revolution in communication. A mere six years and 500 million friends later, Mark Zuckerberg is the youngest billionaire in history... but for this entrepreneur, success leads to both personal and legal complications.`,
    posterURL: `https://m.media-amazon.com/images/M/MV5BOGUyZDUxZjEtMmIzMC00MzlmLTg4MGItZWJmMzBhZjE0Mjc1XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg`,
    rating: 7.7,
    commentsNumber: 94
  },
  {
    id: 18,
    title: `Point Break`,
    originalTitle: `Point Break`,
    year: 1991,
    duration: `2h 2m`,
    genre: `Action`,
    ageLimit: `R`,
    releaseDate: `10 July 1991`,
    country: `USA`,
    story: `An F.B.I. Agent goes undercover to catch a gang of surfers who may be bank robbers.`,
    posterURL: `https://m.media-amazon.com/images/M/MV5BNWVjZWFmYjItZGJlOC00YTllLWE4YjctMWY2ZTg5ZjE0MDIyXkEyXkFqcGdeQXVyNDk3NzU2MTQ@._V1_SY1000_SX675_AL_.jpg`,
    rating: 7.2,
    commentsNumber: 80
  },
  {
    id: 19,
    title: `Heat`,
    originalTitle: `Heat`,
    year: 1995,
    duration: `2h 50m`,
    genre: `Crime`,
    ageLimit: `R`,
    releaseDate: `15 December 1995`,
    country: `USA`,
    story: `Neil McCauley leads a group of professional bank robbers, taking down major scores around LA. However after their latest heist goes terribly wrong and ends up in homicide, Det. Vincent Hannah finds a clue and becomes obsessed with the case determined to stop McCauley's crew. Hannah and McCauley are competing against each other in a deadly cat-and-mouse game. Although they are on different sides of the law, they still find huge respect, recognition in each others troubled personal lives and they understand each others motivations - however this won't make them hesitate to do whatever they can to win the battle between them two in this crime saga.`,
    posterURL: `https://m.media-amazon.com/images/M/MV5BNDc0YTQ5NGEtM2NkYS00MWRhLThiNzAtNmY3NWU3YzNkMjIyXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SY1000_CR0,0,661,1000_AL_.jpg`,
    rating: 8.2,
    commentsNumber: 58
  },
  {
    id: 20,
    title: `Spring, Summer, Fall, Winter... and Spring`,
    originalTitle: `Spring, Summer, Fall, Winter... and Spring`,
    year: 2003,
    duration: `1h 43m`,
    genre: `Drama`,
    ageLimit: `R`,
    releaseDate: `19 September 2003`,
    country: `South Korea`,
    story: `A Buddhist monk lives in a temple in the middle of a lake. He is training a child to be a monk. We see the transitions the younger monk goes through as he ages, his discoveries, trials and tribulations, temptations, sins, punishments and atonements.`,
    posterURL: `https://m.media-amazon.com/images/M/MV5BMTI0ODMwOTIxOV5BMl5BanBnXkFtZTcwMzE2NDUyMQ@@._V1_SY1000_SX675_AL_.jpg`,
    rating: 8.1,
    commentsNumber: 40
  },
  {
    id: 21,
    title: `Thunderbolt`,
    originalTitle: `Thunderbolt`,
    year: 1995,
    duration: `1h 50m`,
    genre: `Action`,
    ageLimit: `R`,
    releaseDate: `5 August 1995`,
    country: `Hong Kong`,
    story: `In order to release his kidnapped sister, sports car mechanic Chan Foh To has to beat a supercriminal street racer.`,
    posterURL: `https://m.media-amazon.com/images/M/MV5BNmU1NDZmMDQtZjkxOS00YTQzLTk5ZjgtZjQ2MTRjYjQ2NGNmXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_SY1000_CR0,0,684,1000_AL_.jpg`,
    rating: 6.4,
    commentsNumber: 70
  },
  {
    id: 22,
    title: `I Saw the Devil`,
    originalTitle: `I Saw the Devil`,
    year: 2010,
    duration: `2h 22m`,
    genre: `Action`,
    ageLimit: `Not Rated`,
    releaseDate: `12 August 2010`,
    country: `South Korea`,
    story: `If you thought Oldboy (2003) was the most messed up Korean revenge thriller ever made, think again. This story follows a special agent who is planning on avenging the death of her young pregnant wife after being killed by a serial killer. And as he's on his way to catch the monster, he's soon starting to become in one. The results are harrowing.`,
    posterURL: `https://m.media-amazon.com/images/M/MV5BMTY1NjE1NTE0MV5BMl5BanBnXkFtZTcwOTYzNjUzNA@@._V1_SY1000_CR0,0,674,1000_AL_.jpg`,
    rating: 7.8,
    commentsNumber: 55
  },
  {
    id: 23,
    title: `The Intouchables`,
    originalTitle: `The Intouchables`,
    year: 2011,
    duration: `1h 52m`,
    genre: `Comedy`,
    ageLimit: `R`,
    releaseDate: `23 September 2011`,
    country: `France`,
    story: `A rich quadriplegic, living in a mansion in Paris, requires a live-in carer. A young offender turns up for an interview, but he is not really looking to get the job. However, to his surprise, he is hired. The two men then develop a close friendship.`,
    posterURL: `https://m.media-amazon.com/images/M/MV5BMTYxNDA3MDQwNl5BMl5BanBnXkFtZTcwNTU4Mzc1Nw@@._V1_SY1000_CR0,0,674,1000_AL_.jpg`,
    rating: 8.5,
    commentsNumber: 88
  },
  {
    id: 24,
    title: `Inception`,
    originalTitle: `Inception`,
    year: 2010,
    duration: `2h 28m`,
    genre: `Adventure`,
    ageLimit: `PG-13`,
    releaseDate: `8 July 2010`,
    country: `USA`,
    story: `Dom Cobb is a skilled thief, the absolute best in the dangerous art of stealing valuable secrets from deep within the subconscious during the dream state. Cobb's rare ability has made him a coveted player in treacherous world of corporate espionage, but it has also made him an international fugitive and cost him everything he has ever loved. Now Cobb is being offered a chance at redemption. One last job could give him his life back but only if he can accomplish the impossible. Cobb and his team's task is not to steal an idea but to plant one. If they succeed, it could be the perfect crime...`,
    posterURL: `https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_SY1000_CR0,0,675,1000_AL_.jpg`,
    rating: 8.8,
    commentsNumber: 32
  },
  {
    id: 25,
    title: `The Shawshank Redemption`,
    originalTitle: `The Shawshank Redemption`,
    year: 1994,
    duration: `2h 22m`,
    genre: `Drama`,
    ageLimit: `R`,
    releaseDate: `10 September 1994`,
    country: `USA`,
    story: `Chronicles the experiences of a formerly successful banker as a prisoner in the gloomy jailhouse of Shawshank after being found guilty of a crime he did not commit. The film portrays the man's unique way of dealing with his new, torturous life; along the way he befriends a number of fellow prisoners, most notably a wise long-term inmate named Red.`,
    posterURL: `https://m.media-amazon.com/images/M/MV5BMDFkYTc0MGEtZmNhMC00ZDIzLWFmNTEtODM1ZmRlYWMwMWFmXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg`,
    rating: 9.3,
    commentsNumber: 59
  }
];

// Данные списков.
const lists = [
  {
    id: `all`,
    name: `All movies`,
    moviesNumber: null
  },
  {
    id: `watchlist`,
    name: `Watchlist`,
    moviesNumber: 15 // заменить на реальные значения
  },
  {
    id: `history`,
    name: `History`,
    moviesNumber: 250 // заменить на реальные значения
  },
  {
    id: `favorites`,
    name: `Favorites`,
    moviesNumber: 30 // заменить на реальные значения
  },
  {
    id: `stats`,
    name: `Stats`,
    moviesNumber: null
  }
];

export {lists, movies};
